problem :: changing browser from Firefox to Chrome - encountered error:
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

using Chrome version If you are using Chrome version 92, please download ChromeDriver 92.0.4515.107

after attempting to use ChromeDriver - ran into a bunch of issues - possibly due to version or an outdated driver

attempting to go back to Firefox()