installed Firefox on system added sele_browser(ur):     takes in url and opens it in an instance of Firefox
problem - attempting to run have a web driver error:

selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

going to attempt to run on native Chrome