downloaded geckodriver :: placed in project folder https://github.com/mozilla/geckodriver/releases
good tutorial ::
https://tkxel.com/blog/download-and-install-selenium-webdriver-get-started-with-test-automation/

problem :: still experiencing a time-out error - need to research further
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=https%3A//smartweb.madisoncountysheriffal.org/SmartWEBClient/Jail.aspx&c=UTF-8&d=The%20server%20at%20smartweb.madisoncountysheriffal.org%20is%20taking%20too%20long%20to%20respond.

error found! - was attempting to use https to access the page - but website is unsecured!!!!

website accessed with http://